### ISSUE TITLE
github 里该成 template 或许会更方便

### ISSUE THREAD

**Issue by sailist** [tianyu-su/sdu-theis-template#1]
毕竟 fork 只能 public，但改成 template 后 use template 就可以变成自己的 private repository 了。

> 我费心调完样式后发现你做的更好，赞死了（

**Comment by tianyu-su** [comment]
word模板改成template嘛？我提供了个dotx文件

**Comment by sailist** [comment]
是这个 repo 本身，如果 fork 的话不能改成 private，可以在 settings 里把这个 repo 本身改成 template。

**Comment by tianyu-su** [comment]
woow，get新技能
